#! /usr/bin/env sh

error() {
    echo "$PROGRAM: $@" 1>&2
    exit 1
}

check_dependencies() {
    `command -v crc32 > /dev/null`
    if [ $? -ne 0 ] ; then
        error "program crc32 missing."
    fi
}

verify() {
    echo $1 `crc32 $1`
}

main() {
    check_dependencies

    verify $1
}


PROGRAM=$(basename $0)

main "$1"
